apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoApp
  template:
    metadata:
      labels:
        app: todopp 
    spec:
      containers:
        - name: todo-app
          image: todo-app
          imagePullPolicy: IfNotPresent